Add cars
Sf-60-Ruby-Cisco/BE-Ruby-Project pull request #25
Opened 2022-08-22 15:17 UTC by Syncwell-257

"Add cars" added.

2022-08-23 10:17 UTC, apoltieva commented on db/schema.rb
> +
Why do we have 2 tables?

2022-08-23 10:19 UTC, apoltieva reviewed
Testing views is a bit excessive

2022-08-23 10:20 UTC, apoltieva commented
Why is our model named CarIndex when the DB schema specifies only a car model?

2022-08-23 10:22 UTC, apoltieva commented
And yes, rn cars are not linked to any user because there's no association. Read https://guides.rubyonrails.org/association_basics.html

2022-08-23 10:25 UTC, apoltieva requested changes
I also see that you have one migration but 2 tables in the schema. It's because you've deleted the migrations file, but that doesn't change the database. If you migrated something you didn't want to, you should either reverse the migration or create a new one that would reverse the changes

2022-09-05 13:30 UTC, Snick555 commented on app/controllers/cars_controller.rb
> +    @cars = Car.where(user: current_user)
```suggestion
    @cars = current_user.cars
```

2022-09-05 13:30 UTC, Snick555 commented on app/controllers/cars_controller.rb
> +    @car = Car.new(car_params.merge(user: current_user))
```suggestion
    @car = current_user.cars.new(car_params)
```

2022-09-06 10:46 UTC, apoltieva approved these changes

2022-09-06 10:47 UTC, merged