Rspec user
Sf-60-Ruby-Cisco/BE-Ruby-Project pull request #47
Opened 2022-09-19 09:58 UTC by Stoyan83

2022-09-19 13:44 UTC, Snick555 commented
Don't use commits from another PR, it's hard to track changes

2022-09-20 09:53 UTC, apoltieva requested changes

2022-09-20 09:53 UTC, apoltieva commented on spec/requests/users_spec.rb
> +  new_user = FactoryBot.create :user
Don't use local variables, use let() https://relishapp.com/rspec/rspec-core/v/2-11/docs/helper-methods/let-and-let

2022-09-20 09:53 UTC, apoltieva commented on spec/requests/users_spec.rb
> +    new_user.created_at = nil
let(:new_user) { FactoryBot.create(:user, created_at: nil) }

2022-09-21 06:04 UTC, apoltieva approved these changes

2022-09-21 13:08 UTC, merged